### ISSUE TITLE
Add breadcrumbs to website

### ISSUE THREAD

**Issue by aastha985** [aastha985/AAF_Website#6]

**Comment by AkshadK7** [comment]
Where do you exactly want the breadcrumb to be placed ???

**Comment by aastha985** [comment]
Hi! @AkshadK7 The breadcrumbs are needed at 3 places. I have highlighted with yellow in each of the pages( add a little margin above and below the breadcrumbs too).Do let me know if you want to be assigned to this or if you need any help :)
1. The show page of each blog
![image](https://user-images.githubusercontent.com/55681187/94347854-74661780-0055-11eb-8297-a3fba0f2d889.png)
2. The show page of each opportunity
![image](https://user-images.githubusercontent.com/55681187/94347877-b000e180-0055-11eb-8ba7-72663a351c48.png)
3. The index page of each opportunity.
![image](https://user-images.githubusercontent.com/55681187/94347891-cdce4680-0055-11eb-93b1-ed5fe25ccf6b.png)

**Comment by AkshadK7** [comment]
OK Got it !

Yup, you can surely Assign me the task !

I'll complete it soon and send a PR by 1st October so it could help me out for the HacktoberFest 2020 too.

P.S:  You can always check out my Web Dev skills through my profile :)

**Comment by aastha985** [comment]
Assigned 👍 @AkshadK7
